name: geneformer
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - igraph
  - ipykernel
  - ipython
  - pip=24.0
  - python=3.10.13
  - pip:
      - anndata
      - datasets
      - h5py
      - huggingface-hub
      - matplotlib
      - networkx
      - numba
      - numpy<2.0.0
      - pandas
      - pyarrow
      - scanpy
      - scikit-learn
      - scipy
      - seaborn
      - statsmodels
      - tdigest
      - torch
      - transformers
      - umap-learn
