output_path: "/scratch/indikar_root/indikar1/shared_data/geneformer/"
ihsc_path: "/scratch/indikar_root/indikar1/cstansbu/HSC/scanpy/clustered.anndata.h5ad"
ts_dir: "/nfs/turbo/umms-indikar/shared/projects/DGC/data/tabula_sapiens/extract/"
name_path: "/nfs/turbo/umms-indikar/shared/projects/geneformer/geneformer/gene_name_id_dict.pkl"
token_path: "/nfs/turbo/umms-indikar/shared/projects/geneformer/token_dictionary.pkl"
median_path: "/nfs/turbo/umms-indikar/shared/projects/geneformer/geneformer/gene_median_dictionary.pkl"
token_mapping_path: "/nfs/turbo/umms-indikar/shared/projects/geneformer/token_mappings.csv"
pellin_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/pellin_2019/pellin.anndata.h5ad"
weng_dir: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/weng_2024/scanpy_objects/"